# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Playwrigth tests           #Solo el nombre, se puede cambiar

on:                              #Que eventos activan el flujo
  push:                          # Este evento se activa cuando se realiza un "push" (es decir, se suben cambios) a una rama en el repositorio.
    branches: [ "main" ]         # Indica que el flujo de trabajo solo se activará si el "push" se realiza en la rama "main".
  pull_request:                  #Este evento se activa cuando se abre, cierra, o actualiza un "pull request" en el repositorio.
    branches: [ "main" ]         #Indica que el flujo de trabajo solo se activará si el "pull request" afecta a la rama "main".

permissions:
  contents: read

jobs:
  build:                         #Es el nombre del build. Lo puedo cambiar. Por ej: tests:

    runs-on: ubuntu-latest       #En que entorno se corre. runs-on: windows-latest , runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies     #Flake8 es un lintern, no debe hacer falta. Instalo pytest
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-playwright            
        python -m pip install playwright
    - name: Install browsers                         # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi si tuviera un requirements
      run: |
        python -m playwright install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
